language: groovy
jdk:
  - openjdk7

# To solve BufferOverflow on OpenJDK7 we setup short hostname (<64characters)
# See:
#   - ISSUE-5227: https://github.com/travis-ci/travis-ci/issues/5227
#   - https://docs.travis-ci.com/user/hostname
#   - https://github.com/mockito/mockito/blob/master/.travis.yml
addons:
  hosts:
    - catch-afpersistence
  hostname: catch-afpersistence

before_install:
  # Install inline plugin dependencies
  - pwd
  - cd ../..
  - git clone https://github.com/annotationframework/AfSecurity.git annotationframework/AfSecurity
  - cd annotationframework/AfPersistence

script: ./grailsw refresh-dependencies
  && ./grailsw "test-app unit:"
  && ./grailsw "test-app integration:"